--Sequences:
drop SEQUENCE PRODUCT_SEQUENCE;

CREATE SEQUENCE  "STARTCODING0TO1"."PRODUCT_SEQUENCE" MINVALUE 1 MAXVALUE 1000 INCREMENT BY 1 START WITH 1 CACHE 20 ORDER  CYCLE  NOKEEP  NOSCALE  GLOBAL ;

drop sequence USER_SEQUENCE;

CREATE SEQUENCE  "STARTCODING0TO1"."USER_SEQUENCE"  MINVALUE 1 MAXVALUE 1000 INCREMENT BY 1 START WITH 3 NOCACHE  ORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;

drop sequence ADDRESS_ID_SEQ;

CREATE SEQUENCE  "STARTCODING0TO1"."ADDRESS_ID_SEQ"  MINVALUE 1 MAXVALUE 1000 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;

CREATE SEQUENCE order_id_sequence
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

--Address:

  CREATE TABLE "STARTCODING0TO1"."ADDRESS"
   (	"ADDRESS_ID" NUMBER(10,0) NOT NULL ENABLE,
	"ADMIN_DETAILS_ID" NUMBER(10,0),
	"CUSTOMER_DETAILS_ID" NUMBER(10,0),
	"SELLER_DETAILS_ID" NUMBER(10,0),
	"PINCODE" NUMBER(19,0),
	"USER_ID" VARCHAR2(200 CHAR),
	"CITY" VARCHAR2(255 CHAR),
	"HOUSE_NO" VARCHAR2(255 CHAR),
	"LANDMARK" VARCHAR2(255 CHAR),
	"STATE" VARCHAR2(255 CHAR),
	"STREET" VARCHAR2(255 CHAR),
	 PRIMARY KEY ("ADDRESS_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  TABLESPACE "USERS"  ENABLE,
	 CONSTRAINT "FKOR5NGYLDQO4LM91VBUAU4VN77" FOREIGN KEY ("ADMIN_DETAILS_ID")
	  REFERENCES "STARTCODING0TO1"."ADMIN_DETAILS" ("ADMIN_DETAILS_ID") ENABLE,
	 CONSTRAINT "FKEPPS0EI72SEA63SNQEIWKLTDK" FOREIGN KEY ("CUSTOMER_DETAILS_ID")
	  REFERENCES "STARTCODING0TO1"."CUSTOMER_DETAILS" ("CUSTOMER_ID") ENABLE,
	 CONSTRAINT "FK6I66IJB8TWGCQTETL8EEEED6V" FOREIGN KEY ("USER_ID")
	  REFERENCES "STARTCODING0TO1"."USERS" ("USER_ID") ENABLE,
	 CONSTRAINT "FKMYF00GG4GX40BNJP9DW5X7Q37" FOREIGN KEY ("SELLER_DETAILS_ID")
	  REFERENCES "STARTCODING0TO1"."SELLER_DETAILS" ("SELLER_ID") ON DELETE CASCADE ENABLE
   ) SEGMENT CREATION DEFERRED
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

--Cart:

  CREATE TABLE "STARTCODING0TO1"."CART"
   (	"CART_ID" NUMBER(10,0) NOT NULL ENABLE,
	"CUSTOMER_DETAILS_ID" NUMBER(10,0),
	"QUANTITY" NUMBER(10,0),
	"CREATION_TIME" TIMESTAMP (6),
	"PRODUCT_ID" VARCHAR2(200 CHAR) NOT NULL ENABLE,
	 PRIMARY KEY ("CART_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE,
	 UNIQUE ("PRODUCT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE,
	 CONSTRAINT "FK3D704SLV66TW6X5HMBM6P2X3U" FOREIGN KEY ("PRODUCT_ID")
	  REFERENCES "STARTCODING0TO1"."PRODUCT" ("PRODUCT_ID") ON DELETE CASCADE ENABLE,
	 CONSTRAINT "FKFW7VSOV3WEWBU1VXM3RN2TKPQ" FOREIGN KEY ("CUSTOMER_DETAILS_ID")
	  REFERENCES "STARTCODING0TO1"."CUSTOMER_DETAILS" ("CUSTOMER_ID") ON DELETE CASCADE ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

--CustomerDetails:


  CREATE TABLE "STARTCODING0TO1"."CUSTOMER_DETAILS"
   (	"CUSTOMER_ID" NUMBER(10,0) NOT NULL ENABLE,
	"USER_ID" VARCHAR2(200 CHAR),
	"PREMIUM_CUSTOMER" VARCHAR2(255 CHAR),
	 PRIMARY KEY ("CUSTOMER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE,
	 UNIQUE ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE,
	 CONSTRAINT "FKQIGL94I49I5IWLXTGO6D3Q7MH" FOREIGN KEY ("USER_ID")
	  REFERENCES "STARTCODING0TO1"."USERS" ("USER_ID") ON DELETE CASCADE ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;



--Product:

  CREATE TABLE "STARTCODING0TO1"."PRODUCT"
   (	"DISCOUNT_PRICE" FLOAT(53),
	"PROD_PRICE" FLOAT(53),
	"QUANTITY" NUMBER(10,0),
	"RATING" NUMBER(10,0),
	"SELLER_ID" NUMBER(10,0) NOT NULL ENABLE,
	"TOTAL_REVIEWS" NUMBER(10,0),
	"CREATION_TIME" TIMESTAMP (6),
	"LAST_UPDATE_TIME" TIMESTAMP (6),
	"PRODUCT_ID" VARCHAR2(200 CHAR) NOT NULL ENABLE,
	"BRAND" VARCHAR2(255 CHAR),
	"IMAGE_URL" VARCHAR2(255 CHAR),
	"PROD_AVAILABILITY" VARCHAR2(255 CHAR),
	"PROD_CATEGORY" VARCHAR2(255 CHAR),
	"PROD_SUB_CATEGORY" VARCHAR2(255 CHAR),
	"PRODUCT_DESC" VARCHAR2(255 CHAR),
	"PRODUCT_NAME" VARCHAR2(255 CHAR),
	"PRODUCT_SIZE" VARCHAR2(255 CHAR),
	"VIDEO_URL" VARCHAR2(255 CHAR),
	 PRIMARY KEY ("PRODUCT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE,
	 CONSTRAINT "FKKFXK45LLC3LBO9S03B0OEYUKL" FOREIGN KEY ("SELLER_ID")
	  REFERENCES "STARTCODING0TO1"."SELLER_DETAILS" ("SELLER_ID") ON DELETE CASCADE ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

--SellerDetails:

  CREATE TABLE "STARTCODING0TO1"."SELLER_DETAILS"
   (	"SELLER_ID" NUMBER(10,0) NOT NULL ENABLE,
	"USER_ID" VARCHAR2(200 CHAR),
	"COMPANY_NAME" VARCHAR2(255 CHAR),
	 PRIMARY KEY ("SELLER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE,
	 UNIQUE ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE,
	 CONSTRAINT "FK3NLNBOFQGOD82VBVK2SY2V34L" FOREIGN KEY ("USER_ID")
	  REFERENCES "STARTCODING0TO1"."USERS" ("USER_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

--User:

  CREATE TABLE "STARTCODING0TO1"."USERS"
   (	"CREATION_TIME" TIMESTAMP (6),
	"LAST_UPDATE_TIME" TIMESTAMP (6),
	"PHONE_NUMBER" NUMBER(19,0),
	"USER_ID" VARCHAR2(200 CHAR) NOT NULL ENABLE,
	"EMAIL" VARCHAR2(255 CHAR),
	"FIRST_NAME" VARCHAR2(255 CHAR),
	"LAST_NAME" VARCHAR2(255 CHAR),
	"PASSWORD" VARCHAR2(255 CHAR),
	 PRIMARY KEY ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

--WISHLIST:

  CREATE TABLE "STARTCODING0TO1"."WISHLIST"
   (	"CUSTOMER_DETAILS_ID" NUMBER(10,0) NOT NULL ENABLE,
	"IS_LIKED" NUMBER(1,0),
	"WISHLIST_ID" NUMBER(10,0) NOT NULL ENABLE,
	"CREATION_TIME" TIMESTAMP (6),
	"PRODUCT_ID" VARCHAR2(200 CHAR),
	 CHECK (is_liked in (0,1)) ENABLE,
	 PRIMARY KEY ("WISHLIST_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE,
	 UNIQUE ("PRODUCT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE,
	 CONSTRAINT "FK1JBLVAXU75JRQ95414RWV67DU" FOREIGN KEY ("CUSTOMER_DETAILS_ID")
	  REFERENCES "STARTCODING0TO1"."CUSTOMER_DETAILS" ("CUSTOMER_ID") ON DELETE CASCADE ENABLE,
	 CONSTRAINT "FKQCHEVBFW5WQ0F4UQACNS02RP7" FOREIGN KEY ("PRODUCT_ID")
	  REFERENCES "STARTCODING0TO1"."PRODUCT" ("PRODUCT_ID") ON DELETE CASCADE ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

--  ADMIN_DETAILS:

  CREATE TABLE "STARTCODING0TO1"."ADMIN_DETAILS"
   (	"ADMIN_DETAILS_ID" NUMBER(10,0) NOT NULL ENABLE,
	"USER_ID" VARCHAR2(200 CHAR),
	 PRIMARY KEY ("ADMIN_DETAILS_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  TABLESPACE "USERS"  ENABLE,
	 UNIQUE ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  TABLESPACE "USERS"  ENABLE,
	 CONSTRAINT "FKT3KNSOA3C15NLDH4VMA8FEWRG" FOREIGN KEY ("USER_ID")
	  REFERENCES "STARTCODING0TO1"."USERS" ("USER_ID") ENABLE
   ) SEGMENT CREATION DEFERRED
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;


--Order:

CREATE TABLE "STARTCODING0TO1"."ORDERS"
(
    "ORDER_ID" NUMBER(10,0),
    "CUSTOMER_ID" NUMBER(10,0),
    "PRODUCT_ID" VARCHAR2(200 CHAR),
    "SELLER_ID" NUMBER(10,0),
    "PRICE_PER_PRODUCT" FLOAT(53),
    "QUANTITY" NUMBER(10,0),
    "TOTAL_PRICE" FLOAT(53),
    "ORDER_STATUS" VARCHAR2(255 CHAR),
    "DELIVER_STATUS" VARCHAR2(255 CHAR),
    "PAYMENT_STATUS" VARCHAR2(255 CHAR),
    "ORDER_PLACED_TIME" TIMESTAMP (6),
    "LAST_UPDATE" TIMESTAMP (6),
    "FEED_BACK" VARCHAR2(255 CHAR),
    PRIMARY KEY ("ORDER_ID")
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
    TABLESPACE "USERS"  ENABLE
);